version: '3.9'
services:
  postgres:
    image: postgres
    shm_size: 128mb
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
