export const CURRENCY = {
  US_DOLLAR: 'USD',
  EURO: 'EUR',
  JAPANESE_YEN: 'JPU',
  POUND_STERLING: 'GPB',
  AUSTRALIAN_DOLLAR: 'AUD',
  CANADIAN_DOLLAR: 'CAD',
  SWISS_FRANC: 'CHF',
};

export const CURRENCIES = [
  CURRENCY.US_DOLLAR,
  CURRENCY.EURO,
  CURRENCY.JAPANESE_YEN,
  CURRENCY.POUND_STERLING,
  CURRENCY.AUSTRALIAN_DOLLAR,
  CURRENCY.CANADIAN_DOLLAR,
  CURRENCY.SWISS_FRANC,
];

export const CURRENCY_SYMBOL = {
  [CURRENCY.US_DOLLAR]: '$',
  [CURRENCY.EURO]: '€',
  [CURRENCY.JAPANESE_YEN]: '¥',
  [CURRENCY.POUND_STERLING]: '£',
  [CURRENCY.AUSTRALIAN_DOLLAR]: '$',
  [CURRENCY.CANADIAN_DOLLAR]: '$',
  [CURRENCY.SWISS_FRANC]: '',
};
